create table public.graves (
  id bigint generated by default as identity primary key,
  name text not null,
  section text not null,
  level integer not null,
  birthdate text,
  dod text,
  x text not null default '50%',
  y text not null default '50%',
  created_at timestamptz not null default now()
);

alter table public.graves enable row level security;

create policy "Anyone can view graves"
  on public.graves for select
  using (true);

create policy "Authenticated admins can add graves"
  on public.graves for insert
  to authenticated
  with check (true);

create policy "Authenticated admins can update graves"
  on public.graves for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated admins can remove graves"
  on public.graves for delete
  to authenticated
  using (true);
